### ISSUE TITLE
[CRITICAL] Process crash in 4.5.4

### ISSUE THREAD

**Issue by appcove** [iuscommunity-pkg/python35u-mod_wsgi#1]
Hello,

The recent update to mod_wsgi 4.5.4 is causing wsgi processes to crash.  The author has release 4.5.5 to revert the code that causes this issue.  

https://github.com/GrahamDumpleton/mod_wsgi/blob/4.5.5/docs/release-notes/version-4.5.5.rst

Please push out 4.5.5 ASAP, and if that is not possible, at least remove 4.5.4 from the stable repositories.

As far as I can tell this will crash any mod_wsgi application as soon as apache is restarted after a yum update.

Thanks!
Jason Garber

**Comment by b-harper** [comment]
Hey @appcove,

Thanks for taking the time to contact us.  Currently, IUS has version 4.5.3 in the stable repositories and 4.5.4 in the testing repositories.  Please note,  we typically keep packages in the testing repositories for two weeks before pushing them into the stable repositories.  Seeing that 4.5.4 includes a nasty bug, it will be removed from the testing repositories during tonight's automation run.  

Earlier today, I built 4.5.5, but then noticed that 4.5.6 might be released soon.  I think we are going to hold off for a day or so to see if 4.5.6 gets released. 

Please see [this upstream issue](https://github.com/GrahamDumpleton/mod_wsgi/issues/147) for more information about the issue with 4.5.4.   

-Ben

**Comment by b-harper** [comment]
Looks like 4.5.6 will not be released immediately after 4.5.5.  The 4.5.5 packages will get pushed to the testing repositories during tonight's automation.
